import db from "@/lib/db";
import { addDays, startOfDay, endOfDay, getDay } from "date-fns";

const DAYS_MAP = [
  "SUNDAY",
  "MONDAY",
  "TUESDAY",
  "WEDNESDAY",
  "THURSDAY",
  "FRIDAY",
  "SATURDAY",
];

export async function generateMassesForPeriod(
  organizationId: string,
  startDate: Date = new Date(),
  endDate: Date = addDays(new Date(), 30),
  options?: { ignoreAutoGenerateSetting?: boolean },
): Promise<number> {
  const org = await db.organization.findUnique({
    where: { id: organizationId },
    include: { massScheduleTemplates: true },
  });

  if (!org) {
    return 0;
  }

  if (!options?.ignoreAutoGenerateSetting && !org.autoGenerateMasses) {
    return 0;
  }

  const dailyLimit = Math.min(org.maxMassesPerDay, 5);

  let createdCount = 0;
  // Use differenceInDays to calculate loop count or just loop while current <= end
  let currentDate = startOfDay(startDate);
  const lastDate = startOfDay(endDate);

  while (currentDate <= lastDate) {
    const dayName = DAYS_MAP[getDay(currentDate)];

    const dayTemplates = org.massScheduleTemplates.filter((t) => {
      if (t.dayOfWeek !== dayName || !t.isActive) return false;
      if (
        t.effectiveFrom &&
        startOfDay(currentDate) < startOfDay(t.effectiveFrom)
      ) {
        return false;
      }
      if (
        t.effectiveUntil &&
        startOfDay(currentDate) > startOfDay(t.effectiveUntil)
      ) {
        return false;
      }
      return true;
    });

    if (dayTemplates.length > 0) {
      const existingMasses = await db.mass.findMany({
        where: {
          organizationId,
          date: {
            gte: startOfDay(currentDate),
            lte: endOfDay(currentDate),
          },
        },
      });

      const existingTimes = new Set(existingMasses.map((m) => m.time));
      let dailyCreatedCount = 0;

      for (const template of dayTemplates) {
        if (existingMasses.length + dailyCreatedCount >= dailyLimit) {
          break;
        }

        if (existingTimes.has(template.time)) {
          continue;
        }

        await db.mass.create({
          data: {
            organizationId,
            date: currentDate,
            time: template.time,
            massType: template.massType,
            language: template.language,
            location: template.location,
            templateId: template.id,
            isAutoGenerated: true,
            maxIntentions: 1,
            status: "SCHEDULED",
          },
        });
        createdCount++;
        dailyCreatedCount++;
        existingTimes.add(template.time);
      }
    }
    currentDate = addDays(currentDate, 1);
  }
  return createdCount;
}

type ManualMassPattern = {
  dayOfWeek: string;
  time: string;
  massType: string;
  language: string | null;
  location: string | null;
  celebrant: string | null;
  maxIntentions: number;
};

export async function generateMassesFromExistingMasses(
  organizationId: string,
  startDate: Date = new Date(),
  endDate: Date = addDays(new Date(), 30),
): Promise<number> {
  const org = await db.organization.findUnique({
    where: { id: organizationId },
    select: { maxMassesPerDay: true },
  });

  if (!org) {
    return 0;
  }

  const sourceMasses = await db.mass.findMany({
    where: {
      organizationId,
      isAutoGenerated: false,
      status: { not: "CANCELLED" },
    },
    orderBy: [{ date: "desc" }, { time: "asc" }],
    select: {
      date: true,
      time: true,
      massType: true,
      language: true,
      location: true,
      celebrant: true,
      maxIntentions: true,
    },
  });

  const patternMap = new Map<string, ManualMassPattern>();
  for (const mass of sourceMasses) {
    const dayOfWeek = DAYS_MAP[getDay(mass.date)];
    const key = [
      dayOfWeek,
      mass.time,
      mass.massType,
      mass.language ?? "",
      mass.location ?? "",
      mass.celebrant ?? "",
      mass.maxIntentions,
    ].join("|");

    if (!patternMap.has(key)) {
      patternMap.set(key, {
        dayOfWeek,
        time: mass.time,
        massType: mass.massType,
        language: mass.language,
        location: mass.location,
        celebrant: mass.celebrant,
        maxIntentions: mass.maxIntentions,
      });
    }
  }

  const patterns = Array.from(patternMap.values());
  if (patterns.length === 0) {
    return 0;
  }

  const dailyLimit = Math.min(org.maxMassesPerDay, 5);
  let createdCount = 0;
  let currentDate = startOfDay(startDate);
  const lastDate = startOfDay(endDate);

  while (currentDate <= lastDate) {
    const dayName = DAYS_MAP[getDay(currentDate)];
    const dayPatterns = patterns.filter(
      (pattern) => pattern.dayOfWeek === dayName,
    );

    if (dayPatterns.length > 0) {
      const existingMasses = await db.mass.findMany({
        where: {
          organizationId,
          date: {
            gte: startOfDay(currentDate),
            lte: endOfDay(currentDate),
          },
        },
        select: { time: true },
      });

      const existingTimes = new Set(existingMasses.map((mass) => mass.time));
      let dailyCreatedCount = 0;

      for (const pattern of dayPatterns) {
        if (existingMasses.length + dailyCreatedCount >= dailyLimit) {
          break;
        }

        if (existingTimes.has(pattern.time)) {
          continue;
        }

        await db.mass.create({
          data: {
            organizationId,
            date: currentDate,
            time: pattern.time,
            massType: pattern.massType as any,
            language: pattern.language,
            location: pattern.location,
            celebrant: pattern.celebrant,
            maxIntentions: pattern.maxIntentions,
            isAutoGenerated: true,
            status: "SCHEDULED",
          },
        });

        createdCount++;
        dailyCreatedCount++;
        existingTimes.add(pattern.time);
      }
    }

    currentDate = addDays(currentDate, 1);
  }

  return createdCount;
}
