import db from '@/lib/db';
import { MassType } from '@prisma/client';
import { addDays, startOfDay, endOfDay, getDay } from 'date-fns';

const DAYS_MAP = ['SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'];

export async function generateMassesForPeriod(
    organizationId: string,
    startDate: Date = new Date(),
    endDate: Date = addDays(new Date(), 30)
): Promise<number> {
    const org = await db.organization.findUnique({
        where: { id: organizationId },
        include: { massScheduleTemplates: true },
    });

    if (!org) {
        console.log('Organization not found:', organizationId);
        return 0;
    }

    if (!org.autoGenerateMasses) {
        console.log('Auto-generate masses is disabled for org:', organizationId);
        return 0;
    }

    console.log(
        `Found ${org.massScheduleTemplates.length} templates for org ${organizationId}`
    );

    let createdCount = 0;
    // Use differenceInDays to calculate loop count or just loop while current <= end
    let currentDate = startOfDay(startDate);
    const lastDate = startOfDay(endDate);

    while (currentDate <= lastDate) {
        const dayName = DAYS_MAP[getDay(currentDate)];

        const dayTemplates = org.massScheduleTemplates.filter(
            (t) => t.dayOfWeek === dayName && t.isActive
        );

        if (dayTemplates.length > 0) {
            const existingMasses = await db.mass.findMany({
                where: {
                    organizationId,
                    date: {
                        gte: startOfDay(currentDate),
                        lte: endOfDay(currentDate),
                    },
                },
            });

            const existingTimes = new Set(existingMasses.map((m) => m.time));
            let dailyCreatedCount = 0;

            for (const template of dayTemplates) {
                if (existingMasses.length + dailyCreatedCount >= org.maxMassesPerDay) {
                    console.log(
                        `Max masses per day (${org.maxMassesPerDay}) reached for ${currentDate}`
                    );
                    break;
                }

                if (existingTimes.has(template.time)) {
                    continue;
                }

                await db.mass.create({
                    data: {
                        organizationId,
                        date: currentDate,
                        time: template.time,
                        massType: template.massType,
                        language: template.language,
                        location: template.location,
                        templateId: template.id,
                        isAutoGenerated: true,
                        maxIntentions: 1,
                        status: 'SCHEDULED',
                    },
                });
                createdCount++;
                dailyCreatedCount++;
                existingTimes.add(template.time);
            }
        }
        currentDate = addDays(currentDate, 1);
    }
    return createdCount;
}
